language: 'python'
python:
    - '3.4'
    - '3.5'
    - '3.6'

services:
    - mysql

env:
    - MYSQL_PASSWORD=""

install:
    - pip install -r requirements.txt

# Run tests
script:
    - ./test.sh

