language: 'python'
python:
    - '3.4'
    - '3.5'
    - '3.6'
install:
    - pip install -r requirements.txt

# Run tests
script:
    - ./test.sh

notifications:
    slack: ecse428timemachine:xBdL1nHr6GMzMwAQxYBxNTFR
