version: '3'

services: 
    django:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        ports:
           - '0.0.0.0:8000:8000'
        network_mode: 'host'
