version: '3'

services:
  timemachine:
    build: ./
    ports:
      - 80:80
    environment:
      - REDIS_HOST=redis
      - MYSQL_HOST=mysql
    depends_on:
      - redis
      - mysql

  timemachine_worker:
    build:
      context: ./
      dockerfile: Dockerfile.worker
    depends_on:
      - redis
      - mysql
    environment:
      - REDIS_HOST=redis
      - MYSQL_HOST=mysql

  redis:
    image: redis
    ports:
      - 6379:6379

  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=timemachine
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db-data:
